# Generated by Django 4.2.6 on 2023-11-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="p1",
            field=models.CharField(default="p1", max_length=30),
        ),
    ]
