# Generated by Django 4.2.6 on 2023-11-18 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_remove_product_p1_product_main_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.main_category"
            ),
        ),
    ]
