# Generated by Django 4.2.6 on 2023-11-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_product_main_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.CharField(max_length=30)),
            ],
        ),
    ]
