# Generated by Django 4.2.6 on 2023-11-25 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.price",
            ),
        ),
    ]
