# Generated by Django 4.2.6 on 2023-11-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_product_price1"),
    ]

    operations = [
        migrations.CreateModel(
            name="color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=30)),
            ],
        ),
    ]
