# Generated by Django 4.2.6 on 2023-12-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_product_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="add_cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                ("qty", models.IntegerField()),
                ("total_price", models.IntegerField()),
            ],
        ),
    ]
