# Generated by Django 4.2.6 on 2023-12-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_add_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="add_cart",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.product",
            ),
        ),
    ]
