# Generated by Django 4.1.3 on 2023-12-23 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_contact_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
